# Generated by Django 5.1.5 on 2025-01-18 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeventosapp', '0002_alter_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 18, 42, 44, 626777)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
