# Generated by Django 5.1.5 on 2025-01-18 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeventosapp', '0003_alter_comentario_fecha_alter_evento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 19, 39, 2, 623284)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=250),
        ),
    ]
