# Generated by Django 5.1.5 on 2025-01-19 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeventosapp', '0004_alter_comentario_fecha_alter_comentario_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 19, 14, 56, 37, 291324)),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='biografia',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
