# Generated by Django 5.1.5 on 2025-01-20 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeventosapp', '0005_alter_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url_img',
            field=models.URLField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 9, 32, 5, 230653)),
        ),
    ]
