# Generated by Django 5.1.5 on 2025-01-20 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webeventosapp', '0007_alter_comentario_fecha_alter_evento_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 10, 9, 0, 951596)),
        ),
    ]
